export enum SagaActions {
  FETCH_BOARDS = "FETCH_BOARDS",
  FETCH_BOARDS_FAILED = "FETCH_BOARDS_FAILED",
  CREATE_BOARD = "CREATE_BOARD",
  DELETE_BOARD = "DELETE_BOARD",

  FETCH_TASKS = "FETCH_TASKS",
  COMPLETE_TASK = "COMPLETE_TASK",
  FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED",
  CREATE_TASK = "CREATE_TASK",
  DELETE_TASK = "DELETE_TASK",
}
